Repository cpaech/ProjectCharlie, pull requests merged in 2025-07, with the labels that each got.

#76 Magic numbers controller more
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/Model.java
Labels: refactor

#77 Update Main.java for Javadoc
  core/src/main/java/io/github/cpaech/charlie/Main.java
Labels: documentation

#78 Fixes Ball Collision / ball does no longer get stuck
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/Model.java
Labels: bug

#86 Refactor mvc java
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/Main.java
  core/src/main/java/io/github/cpaech/charlie/Model.java
  core/src/main/java/io/github/cpaech/charlie/View.java
Labels: documentation

#105 New ai feature
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/Main.java
  core/src/main/java/io/github/cpaech/charlie/MenuView.java
  core/src/main/java/io/github/cpaech/charlie/Model.java
Labels: enhancement

#107 Graphical overhaul
  assets/PongBackground.png
  assets/PongBackground2.png
  assets/PongTitle.png
  assets/numbers.png
  assets/numbers.txt
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/MenuView.java
  core/src/main/java/io/github/cpaech/charlie/View.java
Labels: enhancement

#108 Branch for qol enhancements
  core/src/main/java/io/github/cpaech/charlie/Controller.java
  core/src/main/java/io/github/cpaech/charlie/Model.java
Labels: enhancement
